# Changes here will be overwritten by Copier
_commit: v2.1.2
_src_path: gh:lincc-frameworks/python-project-template
author_email: dalal.64@osu.edu
author_name: Nihar Dalal
create_example_module: true
custom_install: true
enforce_style:
- ruff_lint
- ruff_format
failure_notification: []
include_benchmarks: true
include_docs: true
include_notebooks: true
mypy_type_checking: none
package_name: psfsim
project_license: MIT
project_name: psfsim
project_organization: Roman-HLIS-Cosmology-PIT
python_versions:
- '3.11'
- '3.12'
- '3.13'
test_lowest_version: none
